# Generated by Django 5.0.4 on 2024-05-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sysadmin_instance_base_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=100, unique=True)),
                ('instance_name', models.CharField(max_length=100)),
                ('instance_cpu_size', models.IntegerField()),
                ('instance_memory_size', models.IntegerField()),
                ('instance_system_disk_type', models.CharField(max_length=100)),
                ('instance_system_disk_size', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sysadmin_instance_cloud_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cloud_iam_uid', models.CharField(max_length=300)),
                ('cloud_iam_name', models.CharField(max_length=300)),
                ('instance_id', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cloud_iam_uid', 'instance_id'], name='sysadmin_sy_cloud_i_437c46_idx')],
            },
        ),
        migrations.CreateModel(
            name='sysadmin_instance_connect_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['instance_id'], name='sysadmin_sy_instanc_6591e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='sysadmin_instance_data_disk_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=100)),
                ('instance_data_disk_region', models.CharField(max_length=100)),
                ('instance_data_disk_zone', models.CharField(max_length=100)),
                ('instance_data_disk_type', models.CharField(max_length=100)),
                ('instance_data_disk_size', models.IntegerField()),
                ('instance_data_disk_uuid', models.CharField(max_length=300)),
                ('instance_data_disk_path', models.CharField(max_length=300)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['instance_id'], name='sysadmin_sy_instanc_580546_idx')],
            },
        ),
        migrations.CreateModel(
            name='sysadmin_instance_tags_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=100)),
                ('tag_key', models.CharField(choices=[('Environment', '环境'), ('Project', '项目'), ('Service', '服务'), ('Company', '公司'), ('Team', '团队'), ('Owner', '负责人'), ('Role', '权限'), ('Cloud', '云服务商'), ('Region', '地理意义上的区域'), ('Zone', '地理意义上的可用区'), ('Area', '虚拟意义上的区域'), ('Bill', '财务负责人')], max_length=300)),
                ('tag_value', models.CharField(max_length=300)),
                ('tag_status', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['instance_id', 'tag_key'], name='sysadmin_sy_instanc_76d051_idx')],
            },
        ),
    ]
