# Generated by Django 4.1.4 on 2024-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instance_base_info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=100, unique=True)),
                ('instance_name', models.CharField(max_length=100)),
                ('instance_cpu_size', models.IntegerField()),
                ('instance_memory_size', models.IntegerField()),
                ('instance_system_disk_type', models.CharField(max_length=100)),
                ('instance_system_disk_size', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
