# Generated by Django 5.0.4 on 2024-06-13 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceBaseInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=100, unique=True, verbose_name='Instance ID')),
                ('instance_name', models.CharField(max_length=100)),
                ('instance_cpu_size', models.IntegerField()),
                ('instance_memory_size', models.IntegerField()),
                ('instance_system_disk_type', models.CharField(max_length=100)),
                ('instance_system_disk_size', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Task Name')),
                ('status', models.CharField(choices=[('u', 'Not Started'), ('e', 'Executing'), ('f', 'Finished')], max_length=1, verbose_name='Task Status')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerraformCodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('block_type', models.CharField(max_length=100)),
                ('block_label', models.CharField(max_length=100)),
                ('block_label_name', models.CharField(max_length=100)),
                ('block_context', models.TextField()),
                ('relation_id', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_type', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.publisher')),
            ],
        ),
    ]
