# Generated by Django 5.0.4 on 2024-06-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Task Name')),
                ('status', models.CharField(choices=[('u', 'Not Started'), ('e', 'Executing'), ('f', 'Finished')], max_length=1, verbose_name='Task Status')),
            ],
        ),
    ]
