# Generated by Django 5.0.4 on 2024-06-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_terraformenvironments_terraformenvironmenttemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terraformcodetemplate',
            name='cloud',
        ),
        migrations.RemoveField(
            model_name='terraformcodetemplate',
            name='version',
        ),
    ]
