# Generated by Django 5.0.4 on 2024-06-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_rename_task_task_task_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task_list',
            new_name='TaskList',
        ),
    ]
