# Generated by Django 5.0.4 on 2024-06-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_remove_terraformcodetemplate_module_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terraformcodetemplate',
            old_name='relation_id',
            new_name='code_id',
        ),
    ]
