# Generated by Django 5.0.4 on 2024-06-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_rename_relation_id_terraformcodetemplate_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformcodetemplate',
            name='file_name',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
    ]
