# Generated by Django 5.0.4 on 2024-06-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_terraformcodetemplate_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformcodetemplate',
            name='module',
            field=models.CharField(default='teo', max_length=100),
            preserve_default=False,
        ),
    ]
