# Generated by Django 5.0.4 on 2024-06-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_author_rename_name_book_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(max_length=30),
        ),
    ]
