# Generated by Django 5.0.4 on 2024-06-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_terraformcodetemplate_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformCodes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('code_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='terraformcodetemplate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='terraformenvironments',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='terraformenvironmenttemplate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
