# Generated by Django 5.0.4 on 2024-06-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_terraformcodes_alter_terraformcodetemplate_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TerraformCodes',
            new_name='TerraformCode',
        ),
        migrations.RenameModel(
            old_name='TerraformEnvironments',
            new_name='TerraformEnvironment',
        ),
    ]
