# Generated by Django 5.0.4 on 2024-06-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_rename_terraformcodes_terraformcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terraformcodetemplate',
            old_name='code_id',
            new_name='code_template_id',
        ),
    ]
