# Generated by Django 5.0.4 on 2024-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0010_rename_code_id_terraformcodetemplate_code_template_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terraformenvironment',
            old_name='template_id',
            new_name='env_template_id',
        ),
        migrations.RenameField(
            model_name='terraformenvironmenttemplate',
            old_name='template_id',
            new_name='env_template_id',
        ),
        migrations.AddField(
            model_name='terraformcode',
            name='code_template_id',
            field=models.CharField(default='1985F258-DD45-49CB-B22D-B42C068F370B', max_length=100),
            preserve_default=False,
        ),
    ]
