# Generated by Django 5.0.4 on 2024-06-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0011_rename_template_id_terraformenvironment_env_template_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terraformcodetemplate',
            name='env_id',
        ),
        migrations.AddField(
            model_name='terraformcode',
            name='env_id',
            field=models.CharField(default='1985F258-DD45-49CB-B22D-B42C068F370B', max_length=100),
            preserve_default=False,
        ),
    ]
