# Generated by Django 5.0.4 on 2024-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0012_remove_terraformcodetemplate_env_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformenvironmenttemplate',
            name='remark',
            field=models.CharField(default='初始化配置', max_length=300),
            preserve_default=False,
        ),
    ]
