# Generated by Django 5.0.4 on 2024-06-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0013_terraformenvironmenttemplate_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terraformcode',
            name='code_id',
        ),
    ]
