# Generated by Django 5.0.4 on 2024-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0014_remove_terraformcode_code_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terraformenvironment',
            old_name='backend_object_name',
            new_name='backend_bucket',
        ),
        migrations.RenameField(
            model_name='terraformenvironment',
            old_name='backend_object_type',
            new_name='backend_region',
        ),
        migrations.AddField(
            model_name='terraformenvironment',
            name='backend_type',
            field=models.CharField(default='ap-singapore', max_length=100),
            preserve_default=False,
        ),
    ]
