# Generated by Django 5.0.4 on 2024-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0015_rename_backend_object_name_terraformenvironment_backend_bucket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformAtModule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('src_module', models.CharField(max_length=100)),
                ('src_output', models.CharField(max_length=100)),
                ('dest_module', models.CharField(max_length=100)),
                ('dest_input', models.CharField(max_length=100)),
                ('code_id', models.CharField(max_length=100)),
                ('code_template_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='terraformcode',
            name='code_id',
            field=models.CharField(default='sdf', max_length=100),
            preserve_default=False,
        ),
    ]
