# Generated by Django 5.0.4 on 2024-06-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0016_terraformatmodule_terraformcode_code_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TerraformAtModule',
            new_name='TerraformEnvironmentAtModule',
        ),
    ]
