# Generated by Django 5.0.4 on 2024-06-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0017_rename_terraformatmodule_terraformenvironmentatmodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terraformcodetemplate',
            name='module',
        ),
        migrations.AddField(
            model_name='terraformcode',
            name='module',
            field=models.CharField(default='gff', max_length=100),
            preserve_default=False,
        ),
    ]
