# Generated by Django 5.0.4 on 2024-06-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0018_remove_terraformcodetemplate_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformCodeAtModule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('src_module', models.CharField(max_length=100)),
                ('src_output', models.CharField(max_length=100)),
                ('dest_module', models.CharField(max_length=100)),
                ('dest_input', models.CharField(max_length=100)),
                ('code_template_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TerraformEnvironmentAtModule',
        ),
    ]
