# Generated by Django 5.0.4 on 2024-06-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0019_terraformcodeatmodule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terraformcode',
            name='module',
        ),
        migrations.AddField(
            model_name='terraformcodetemplate',
            name='module',
            field=models.CharField(default='sdf', max_length=100),
            preserve_default=False,
        ),
    ]
