# Generated by Django 5.0.4 on 2024-06-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0020_remove_terraformcode_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformOutputCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('output_type', models.CharField(max_length=100)),
                ('code_id', models.CharField(max_length=100)),
                ('at_module_id', models.CharField(max_length=100)),
                ('output_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='terraformcodeatmodule',
            name='at_module_id',
            field=models.CharField(default='125E8EAE-C9CF-422D-B9F8-2B879EDA89CE', max_length=100),
            preserve_default=False,
        ),
    ]
