# Generated by Django 5.0.4 on 2024-06-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0021_terraformoutputcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformcode',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terraformcodeatmodule',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terraformenvironment',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terraformoutputcode',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
