# Generated by Django 5.0.4 on 2024-06-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0022_terraformcode_status_terraformcodeatmodule_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TerraformCodeAtModule',
            new_name='TerraformOutputAtModule',
        ),
    ]
