# Generated by Django 5.0.4 on 2024-06-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0023_rename_terraformcodeatmodule_terraformoutputatmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformProject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='terraformenvironmenttemplate',
            name='project_id',
            field=models.CharField(default='-1', max_length=100),
            preserve_default=False,
        ),
    ]
