# Generated by Django 5.0.4 on 2024-06-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0024_terraformproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terraformproject',
            name='project_id',
            field=models.CharField(max_length=100, verbose_name='项目ID'),
        ),
        migrations.AlterField(
            model_name='terraformproject',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='项目名称'),
        ),
    ]
