# Generated by Django 5.0.4 on 2024-06-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0025_alter_terraformproject_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformproject',
            name='cloud',
            field=models.CharField(choices=[('alicloud', '阿里云'), ('tencentcloud', '腾讯云'), ('huaweicloud', '华为云')], default='tencentcloud', max_length=100, verbose_name='云厂商'),
            preserve_default=False,
        ),
    ]
