# Generated by Django 5.0.4 on 2024-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0026_terraformproject_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformproject',
            name='area',
            field=models.CharField(default='overseas', max_length=300, verbose_name='区域'),
            preserve_default=False,
        ),
    ]
