# Generated by Django 4.1.4 on 2025-01-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SideBar',
        ),
    ]
